services:
  - type: web
    name: ghibli-vision
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.0.0
    autoDeploy: true
