name = "ghibli-vision"
compatibility_date = "2024-03-31"

# Pages configuration
[build]
command = "npm run cloudflare:build"

[site]
bucket = ".cloudflare/deploy"

# For local development
[dev]
port = 8787
