name = "ghibli-vision-worker"
main = "workers-src/index.ts"
compatibility_date = "2024-03-31"

# Increase CPU time limit for AI image processing
compatibility_flags = ["nodejs_compat"]

# Adjust limits for handling large files and longer processing times
[limits]
cpu_ms = 30000  # 30 seconds of CPU time (much longer than Vercel's 10s limit)
memory_mb = 512  # 512MB of memory

# For local development
[dev]
port = 8787

# Add your environment variables here (for local development)
# For production, you'll need to add these through the Cloudflare dashboard
# or using the wrangler secret commands
[vars]
# OPENAI_API_KEY = ""
# STABILITY_API_KEY = ""
# MIDJOURNEY_API_KEY = ""
# LEONARDO_API_KEY = ""
# NEXT_PUBLIC_SUPABASE_URL = ""
# NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
