name = "ghibli-vision"
main = "workers-src/index.ts"
compatibility_date = "2024-03-31"

# Enable Node.js compatibility
compatibility_flags = ["nodejs_compat"]

# Specify Node.js version
[build.environment]
NODE_VERSION = "20"

# Configure build settings
[build]
command = "pnpm build"
output_directory = ".vercel/output/static"

# For local development
[dev]
port = 8787

# Add your environment variables here (for local development)
# For production, you'll need to add these through the Cloudflare dashboard
# or using the wrangler secret commands
[vars]
# OPENAI_API_KEY = ""
# STABILITY_API_KEY = ""
# MIDJOURNEY_API_KEY = ""
# LEONARDO_API_KEY = ""
# NEXT_PUBLIC_SUPABASE_URL = ""
# NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
