name = "ghibli-vision"
compatibility_date = "2024-03-31"

# Cloudflare Pages configuration
[site]
bucket = ".cloudflare/deploy"

[build]
command = "bash ./cloudflare-build-deploy.sh"

# This is the key property Cloudflare Pages is looking for
pages_build_output_dir = ".cloudflare/deploy"

# For local development
[dev]
port = 8787
