name = "ghibli-vision"
compatibility_date = "2024-03-31"

# Pages configuration
pages_build_output_dir = ".cloudflare/deploy"

# Configure build settings
[build]
command = "node cloudflare-build.js"
output_directory = ".cloudflare/deploy"

# For local development
[dev]
port = 8787
