# Configuration for Cloudflare Pages
# This file helps optimize your Next.js application for Cloudflare Pages

# Set build output directory
[build]
command = "npm run cloudflare:build"
output_directory = ".cloudflare/deploy"

# Configure compatibility date
compatibility_date = "2024-03-31"

# Specify Node.js version
[build.environment]
NODE_VERSION = "20"

# Configure compatibility flags
compatibility_flags = ["nodejs_compat"]

# Configure routes for SPA
[routes]
"/*" = { redirect = false, script = false, proxy = false }
