# Configuration for Cloudflare Pages
# This file helps optimize your static site for Cloudflare Pages

# Set build output directory
[build]
command = "bash ./cloudflare-build-deploy.sh"
output_directory = ".cloudflare/deploy"

# Configure compatibility date
compatibility_date = "2024-03-31"

# Specify Node.js version
[build.environment]
NODE_VERSION = "20"

# Configure routes for SPA
[routes]
"/*" = { redirect = false, script = false, proxy = false }
